# Generated by Django 4.1.1 on 2022-09-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='expercince',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='vacancy',
        ),
    ]
