# Generated by Django 4.1.1 on 2022-09-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_jobpost_expercince_remove_jobpost_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='expercince',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='vacancy',
            field=models.IntegerField(null=True),
        ),
    ]
