# Generated by Django 4.1.1 on 2022-09-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobpost_expercince_jobpost_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Rejected', 'rejected'), ('Approved', 'approved')], default='Pending', max_length=20),
        ),
    ]
