# Generated by Django 4.1.1 on 2022-09-15 16:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0005_interview_shadule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='interview_shadule',
            new_name='Shedule',
        ),
    ]
