# Generated by Django 4.1.1 on 2022-09-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_rename_interview_shadule_shedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
