# Generated by Django 4.1.1 on 2022-09-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_alter_contact_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created_on",
            field=models.DateTimeField(),
        ),
    ]
