# Generated by Django 4.1.1 on 2022-09-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0008_alter_contact_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="company",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="job.company"
            ),
        ),
    ]
